before_commands:
    - mkdir -f $HOME/.composer -p
    - cp ./composer-auth.json $HOME/.composer/auth.json
    - php composer.phar install --prefer-dist
    - php composer.phar global require phing/phing --prefer-dist
    - php composer.phar global require kherge/box --prefer-dist


tools:
    php_code_sniffer:
        config:
            standard: PSR2
    php_analyzer: true
    php_code_coverage:
        test_command: vendor/bin/phpspec -c phpspec.yml.travis run
    php_loc:
        excluded_dirs:
          - vendor
          - Tests
          - build
          - bin
