language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
  - hhvm-nightly

env:
  - DEPS='low'
  - DEPS='dev'
  - DEPS='normal'

matrix:
  allow_failures: DEPS='dev'

before_install:
  - composer selfupdate

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPS" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPS" != "low" ]; then composer update; fi;
  - if [ "$DEPS" != "dev" ]; then compsoer update --prefer-lowser; fi;

before_script:
  - echo "<?php if (defined('HHVM_VERSION')) { echo ',@hhvm'; } else { if (PHP_VERSION_ID >= 50400) echo ',@php5.4'; if (PHP_VERSION_ID >= 70000) echo ',@php7'; }" > php_version_tags.php

script:
  - bin/phpspec run --format=pretty
