language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  - DEPS='low'
  - DEPS='dev'
  - DEPS='normal'

before_install:
  - composer selfupdate
  - echo '#!/bin/bash' > install.sh
  - echo -n "composer update" >> install.sh
  - if [ "$DEPS" == "low" ]; then echo -n " --prefer-lowest" >> install.sh; fi;
  - if [ "$DEPS" == "normal" ]; then echo -n " --prefer-stable" >> install.sh; fi;
  - sed -n '/prefer-stable/!p' composer.json > tmp.json && mv tmp.json composer.json;

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - /bin/bash ./install.sh


before_script:
  - echo "<?php if (defined('HHVM_VERSION')) { echo ',@hhvm'; } else { if (PHP_VERSION_ID >= 50400) echo ',@php5.4'; if (PHP_VERSION_ID >= 70000) echo ',@php7'; }" > php_version_tags.php

script:
  - vendor/bin/phpspec run --format=pretty
